services:
  postgres:
    image: postgres:16-alpine
    container_name: uber_data_analytics
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-uber_analytics_silver}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      TZ: ${TZ:-UTC}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
